# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG OWNER=jupyter
ARG BASE_CONTAINER=$OWNER/pyspark-notebook
FROM $BASE_CONTAINER
ARG NB_USER=jovyan
ARG NB_UID=1000
ARG HOME=/home/jovyan

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"

USER root

# RSpark config
ENV R_LIBS_USER "${SPARK_HOME}/R/lib"
RUN fix-permissions "${R_LIBS_USER}"

# R pre-requisites
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    fonts-dejavu \
    gfortran \
    openjdk-8-jdk \
    openjdk-8-jre \
    gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib && chown ${NB_USER} -R /opt/cloudera/

RUN conda install python=3.7 -y 

USER ${NB_UID}

RUN pip install pyspark && \
    pip install findspark

# RUN conda install pyspark findspark -y && \
RUN conda clean -a -y

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

COPY ./src/spark /opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/spark
